; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Feb 14 2020 17:39:37 GMT-0500 (Eastern Standard Time)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X417 U-18 Y0 F6000 ; go to X=0 Y=0

