; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Feb 14 2020 17:39:36 GMT-0500 (Eastern Standard Time)
M280 P0 S90 ; retract BLTouch

