; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Feb 14 2020 17:39:37 GMT-0500 (Eastern Standard Time)


G1 H2 Z5 F6000    ; lift Z relative to current position
M106 S0  ;turn fan off
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors